### ISSUE TITLE
The state name for 'DC' should be 'District of Columbia'

### ISSUE THREAD

**Issue by alexj** [activeprospect/leadconduit-types#64]
Right now it just returns 'DC'

**Comment by alexj** [comment]
Has this been deployed?

**Comment by zalary** [comment]
answering only because Chris and Jonathan are out today:  Yes.  It was a minor semver bump which was picked up by the API the last time it was updated, and they deployed this morning to fix the gender components thing.  (also yes because i tested it  https://next.leadconduit.com/events/5751b400f650508f149bbe28?event_id=5751b400f650508f149bbe29&source_id=54c13027deb73b38257ddb07&flow_id=5720e68000c25465689d6774&type=source&start=2016-06-03&end=2016-06-03 )

**Comment by alexj** [comment]
awesome, thanks Zal!
