### ISSUE TITLE
add Canadian province names

### ISSUE THREAD

**Issue by cgrayson** [activeprospect/leadconduit-types#87]
Requested by a customer via [Intercom](https://activeprospect.slack.com/archives/intercom/p1485188265000002) - translation from the two-letter codes to full names (see [Wikipedia](https://en.wikipedia.org/wiki/Provinces_and_territories_of_Canada#Provinces)): 

| 2-letter code | full name |
| --- | --- |
| ON | Ontario |
| BC | British Columbia |
| QC | Quebec |
| AB | Alberta |
| NS | Nova Scotia |
| SK | Saskatchawan |
| NL | Newfoundland and Labrador |
| MB | Manitoba |
| NB | New Brunswick |
| PE | Prince Edward Island |

**Comment by cgrayson** [comment]
I think this is simply adding the translations to [this array](https://github.com/activeprospect/leadconduit-types/blob/master/src/types/state.coffee#L4)… that seem 👌 to you, @alexkwolfe? Or do you see anything else to change (e.g., the type name "state" won't be perfectly accurate anymore).

**Comment by alexkwolfe** [comment]
That should do it.

**Comment by alexkwolfe** [comment]
I wonder if we should have a country code property.

**Comment by alexkwolfe** [comment]
On second thought, maybe no country code is required. 

This is the same problem we have with phone type. It's a non-issue at the moment with the state type because there are no duplicate US and Canadian state abbreviations. But if we were to add a third country that had a duplicate code, then the state type would need to be told which country we're dealing with in order to properly assign the full name.

So I propose we punt on worrying about the country code property for now. Then later when we figure out how to solve this issue with the phone type, we can apply the same solution to the state type.

**Comment by cgrayson** [comment]
Fair enough. (For the record see related: #42.)
